export interface Stock {
    name:string,
    description:string,
    country:string,
    founded:string,
    ipo : string,
    industry:string,
    sector:string,
    employees:string,
    ceo:string,
    address:string,
    phone:string,
    website:string,
    symbol:string,
    exchange:string,
    currency:string,
    cik:string,
    cusip:string,
    isin:string,
    employer:string,
    sic:string,
    executives:Record<string,string>
}
