import {Signal} from "signal-polyfill";
import {Todo} from "./Todo.ts";
import {guid} from "../utils/guid.ts";

const mockTitle:string[] = [
    "Complete report for Q1 sales analysis",
    "Schedule meeting with marketing team",
    "Research new project management software options",
    "Prepare presentation slides for client meeting",
    "Review and finalize budget for upcoming quarter",
    "Call supplier to inquire about delivery status",
    "Send follow-up email to potential client",
    "Attend webinar on productivity tips",
    "Organize team-building activity",
    "Update company website with latest news",
    "Review and update employee handbook",
    "Draft agenda for next board meeting",
    "Conduct performance review with team member",
    "Brainstorm ideas for new product features",
    "Create social media content calendar",
    "Order office supplies",
    "Follow up with vendor regarding invoice discrepancy",
    "Attend networking event",
    "Schedule training session for new employees",
    "Prepare expense report",
    "Research industry trends",
    "Meet with accountant to discuss tax implications",
    "Develop marketing campaign for new product launch",
    "Review and approve time-off requests",
    "Update project timelines",
    "Arrange travel accommodations for upcoming conference",
    "Complete online training course",
    "Evaluate customer feedback",
    "Test new software update",
    "Coordinate logistics for company retreat",
    "Respond to customer inquiries",
    "Submit proposal for client project",
    "Review contracts with legal team",
    "Attend trade show",
    "Send out monthly newsletter",
    "Set up team meeting to discuss project progress",
    "Create tutorial videos for product demonstration",
    "Research potential partnerships",
    "Organize files and documents",
    "Attend industry conference",
    "Conduct market research",
    "Schedule maintenance for office equipment",
    "Participate in industry webinar",
    "Review and update company policies",
    "Prepare for quarterly review meeting",
    "Host webinar on industry best practices",
    "Attend professional development workshop",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly goals",
    "Create training materials for new hires",
    "Develop marketing strategy for upcoming promotion",
    "Review customer testimonials",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
 "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",


 "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients",
    "Schedule performance review meetings",
    "Create social media advertising campaign",
    "Prepare for client meeting",
    "Review and revise product roadmap",
    "Update customer database",
    "Coordinate with HR for recruitment efforts",
    "Attend team brainstorming session",
    "Prepare agenda for team meeting",
    "Respond to urgent emails",
    "Schedule team training session",
    "Review and approve expenses",
    "Follow up on leads",
    "Prepare for trade show",
    "Send out press release",
    "Attend product demo",
    "Review sales pipeline",
    "Plan company event",
    "Create content calendar for social media",
    "Coordinate with design team for new product launch",
    "Respond to customer complaints",
    "Schedule team-building activity",
    "Attend industry conference",
    "Conduct employee performance evaluations",
    "Prepare for investor meeting",
    "Review and update employee training materials",
    "Research new market opportunities",
    "Attend webinar on industry trends",
    "Update company website",
    "Respond to customer inquiries",
    "Coordinate with sales team for upcoming promotion",
    "Conduct market analysis",
    "Prepare presentation for board meeting",
    "Review and revise company policies",
    "Send out reminder about upcoming deadlines",
    "Finalize quarterly budget",
    "Create training materials for new hires",
    "Develop marketing campaign for new product launch",
    "Review customer feedback",
    "Coordinate with IT department for software updates",
    "Evaluate vendor proposals",
    "Prepare for annual audit",
    "Plan team-building outing",
    "Review project budget",
    "Attend leadership training seminar",
    "Update company blog with latest content",
    "Conduct competitor analysis",
    "Send out company-wide announcement",
    "Prepare for upcoming presentation",
    "Review and update marketing materials",
    "Attend industry seminar",
    "Respond to RFP",
    "Organize team meeting to discuss project milestones",
    "Research potential clients"]


export function populateTodosMockData(todos: Signal.State<Todo[]>) {
    const now = new Date();
    const mockTodos = mockTitle.map((title: string) => {

        const createdDate = new Date(now.getFullYear(), now.getMonth(), (now.getDate() - Math.round(Math.random() * 1000)) );
        const calculationDueDate = new Date(createdDate.getFullYear(), createdDate.getMonth(), createdDate.getDate() + (Math.round(Math.random() * 1000)));
        const completionDate = calculationDueDate < now ? calculationDueDate : undefined;
        const dueDate = completionDate ? new Date(completionDate.getFullYear(),completionDate.getMonth(),completionDate.getDate() - Math.round(Math.random() * 10) ) : undefined;
        return ({
            completionDate: completionDate,
            createdTime: createdDate,
            description: Math.round(Math.random() * 10000000).toString(),
            dueDate: dueDate,
            id: guid(),
            lastUpdate: new Date(),
            priority: 'High',
            status: 'Pending',
            title: title
        }) as Todo
    })

    todos.set(mockTodos);
}